import { test, expect } from '@playwright/test';
import fs from 'node:fs/promises';
test('studio loads local assets, restores panels, and validates a draft', async ({page}) => {
  const errors = [], external = [];
  page.on('pageerror', e=>errors.push(e.message));
  page.on('request', request=>{ if (!request.url().startsWith('http://127.0.0.1:3210')) external.push(request.url()); });
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Find the frame. Before you film.'})).toBeVisible();
  await page.getByRole('button',{name:'Try a scene'}).click();
  await expect(page.getByLabel('Describe the scene')).toHaveValue(/metal stool/);
  await expect(page.getByLabel('Camera distance')).toHaveValue('wide');
  await page.getByLabel('Camera distance').selectOption('close');
  await expect(page.getByLabel('Camera distance')).toHaveValue('close');
  await page.getByLabel('Camera distance').selectOption('wide');
  await fs.mkdir('artifacts',{recursive:true});
  await page.screenshot({path:'artifacts/studio-desktop.png',fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole('button',{name:'Render scene'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({path:'artifacts/studio-mobile.png',fullPage:true,animations:'disabled'});
  expect(errors).toEqual([]); expect(external).toEqual([]);
});
test('real render through the UI produces a downloadable panel', async ({page,request}) => {
  test.skip(process.env.FRAME_E2E !== '1', 'Opt in with FRAME_E2E=1; needs downloaded models and capable hardware.');
  test.setTimeout(1800000);
  const errors = [];
  page.on('pageerror', e=>errors.push(e.message));
  await page.goto('/');
  await page.getByLabel('Describe the scene').fill('A pair of dark sunglasses resting on a brushed metal table, a single metal stool in the background, dramatic side lighting, minimalist concrete studio');
  await page.getByLabel('Camera distance').selectOption('close');
  await page.getByRole('spinbutton',{name:'Seed / repeat a composition'}).fill('183');
  await page.getByRole('button',{name:'Render scene'}).click();
  await expect(page.getByRole('button',{name:'Stop render'})).toBeVisible();
  const concurrent = await request.post('/api/render',{data:{prompt:'should not start'}});
  expect(concurrent.status()).toBe(409);
  await expect(page.getByRole('status')).toHaveText('Panel ready',{timeout:1700000});
  await expect(page.getByAltText('Generated cinematic storyboard panel')).toBeVisible();
  await expect(page.locator('#error')).toBeHidden();
  const imageURL = await page.locator('#download').getAttribute('href');
  const response = await request.get(imageURL);
  expect(response.headers()['content-type']).toBe('image/png');
  expect((await response.body()).length).toBeGreaterThan(10000);
  await fs.mkdir('docs/evidence',{recursive:true});
  await page.screenshot({path:'docs/evidence/studio.png',fullPage:true,animations:'disabled'});
  expect(errors).toEqual([]);
});
