import { test, expect } from '@playwright/test';
import fs from 'node:fs/promises';
import { PNG } from 'pngjs';
test('studio loads local assets, restores panels, and validates a draft', async ({page}) => {
  const errors = [], external = [];
  page.on('pageerror', e=>errors.push(e.message));
  page.on('request', request=>{ if (!request.url().startsWith('http://127.0.0.1:3210')) external.push(request.url()); });
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Plan the shot. Bring it to life.'})).toBeVisible();
  await page.getByRole('button',{name:'Use shoot brief'}).click();
  await expect(page.getByLabel('Describe the scene')).toHaveValue(/amber glass/);
  await expect(page.getByLabel('Camera distance')).toHaveValue('close');
  await page.getByLabel('Camera distance').selectOption('close');
  await expect(page.getByLabel('Camera distance')).toHaveValue('close');
  await page.getByLabel('Camera distance').selectOption('wide');
  await fs.mkdir('artifacts',{recursive:true});
  await page.screenshot({path:'artifacts/studio-desktop.png',fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole('button',{name:'Render scene'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({path:'artifacts/studio-mobile.png',fullPage:true,animations:'disabled'});
  expect(errors).toEqual([]); expect(external).toEqual([]);
});
test('real SDXL render preserves color and exports a usable crew board', async ({page,request}) => {
  test.skip(process.env.FRAME_E2E !== '1', 'Opt in with FRAME_E2E=1; needs downloaded models and capable hardware.');
  test.setTimeout(1800000);
  const errors = [];
  page.on('pageerror', e=>errors.push(e.message));
  await page.goto('/');
  await page.getByRole('button',{name:'Use shoot brief'}).click();
  await page.getByRole('button',{name:'Render scene'}).click();
  await expect(page.getByRole('button',{name:'Stop render'})).toBeVisible();
  const concurrent = await request.post('/api/render',{data:{prompt:'should not start'}});
  expect(concurrent.status()).toBe(409);
  await expect(page.getByRole('status')).toHaveText('Panel ready',{timeout:1700000});
  await expect(page.getByAltText('Generated shoot concept frame')).toBeVisible();
  await expect(page.locator('#error')).toBeHidden();
  const imageURL = await page.locator('#download').getAttribute('href');
  const response = await request.get(imageURL);
  expect(response.headers()['content-type']).toBe('image/png');
  const pngBytes = await response.body();
  const pixels = PNG.sync.read(pngBytes);
  expect(pixels.width).toBe(1024); expect(pixels.height).toBe(1024);
  let colored = 0;
  for (let i=0;i<pixels.data.length;i+=4) if (Math.max(...pixels.data.subarray(i,i+3))-Math.min(...pixels.data.subarray(i,i+3))>15) colored++;
  expect(colored/(pixels.width*pixels.height)).toBeGreaterThan(.1);
  await fs.mkdir('docs/evidence',{recursive:true});
  await page.screenshot({path:'docs/evidence/studio.png',fullPage:true,animations:'disabled'});
  await fs.writeFile('docs/evidence/panel.png',pngBytes);
  const metadataURL = await page.locator('#metadata').getAttribute('href');
  await fs.writeFile('docs/evidence/shot-notes.json',await (await request.get(metadataURL)).body());
  await page.getByLabel('Shoot / project name').fill('Skincare launch / crew plan');
  const downloaded = page.waitForEvent('download');
  await page.getByRole('button',{name:'Export printable board'}).click();
  const file = await downloaded;
  await file.saveAs('artifacts/crew-board.html');
  const board = await fs.readFile('artifacts/crew-board.html','utf8');
  expect(board).toContain('Skincare launch / crew plan'); expect(board).toContain('data:image/png;base64,'); expect(board).toContain('white bounce card right');
  await fs.writeFile('docs/evidence/crew-board.html', board);
  await page.getByRole('button',{name:'Reuse brief'}).click();
  await expect(page.getByLabel('Shot title')).toHaveValue('Product hero — morning light');
  expect(errors).toEqual([]);
});
test('setup readiness recovers without refresh and optional upscale does not block rendering', async ({page}) => {
  let ready = false, upscaleReady = false;
  await page.route('**/api/status', route => route.fulfill({ json: {
    sdk:'0.19.1', modelsReady:ready, upscaleReady, active:null, modelError:ready ? null : 'Run npm run setup.'
  } }));
  await page.goto('/');
  await page.getByLabel('Describe the scene').fill('Keep this brief while setup finishes');
  await expect(page.getByRole('button',{name:'Render scene'})).toBeDisabled();
  await expect(page.locator('#setup')).toBeVisible();
  ready = true;
  await expect(page.getByRole('button',{name:'Render scene'})).toBeEnabled({timeout:10000});
  await expect(page.locator('#setup')).toBeHidden();
  await expect(page.locator('#upscale-setup')).toBeVisible();
  await expect(page.getByRole('button',{name:'Upscale 4×'})).toBeDisabled();
  upscaleReady = true;
  await expect(page.locator('#upscale-setup')).toBeHidden({timeout:10000});
  await expect(page.getByLabel('Describe the scene')).toHaveValue('Keep this brief while setup finishes');
});
